petersen = {
 "f2r":"Cyanus silvestris",
 "f2v":"coliocasia",
 "f3r":"Crassulatea",
 "f3v":"",
 "f4r":"Hypericum",
 "f4v":"Cobvulvula ipomea?",
 "f5r":"Paris",
 "f5v":"Parietaria",
 "f6r":"Asclepiades",
 "f6v":"",
 "f7r":"Nymphaea alba",
 "f7v":"",
 "f8r":"Praenanthes",
 "f8v":"Silene",
 "f9r":"Chalidonium magna",
 "f9v":"Viola tricoloris",
 "f10r":"Scabiosa",
 "f10v":"Hellebora? Orientalis",
 "f11r":"Silene scambis",
 "f11v":"Leonotus",
 "f13r":"Tussilago petronites",
 "f13v":"Crassolatea Fetthenne",
 "f14r":"Pfeilkraut - sagittaria",
 "f14v":"Osmodei",
 "f15r":"[Some thistle]",
 "f15v":"Herba Paris",
 "f16r":"Canabis",
 "f16v":"",
 "f17r":"",
 "f17v":"Smilax",
 "f18r":"Ringelblume",
 "f18v":"",
 "f19r":"",
 "f19v":"",
 "f20r":"Moss polytrichnum",
 "f20v":"Fam. compositae",
 "f21r":"Polygonum, Eisenkraut",
 "f21v":"Salvia?",
 "f22r":"",
 "f22v":"",
 "f23r":"Water Veronia, Helleborum",
 "f23v":"",
 "f24r":"Libnis alba Behen",
 "f24v":"Origophyllus",
 "f25r":"",
 "f25v":"Leontopodium, Edelweiss",
 "f26r":"gnaphalium",
 "f26v":"verbena foenica",
 "f27r":"Asarium",
 "f27v":"",
 "f28r":"Arum",
 "f28v":"",
 "f29r":"lappa bur[... /illeg]",
 "f29v":"",
 "f30r":"Schuppenwurz?",
 "f30v":"Boragine",
 "f31r":"Hyrciacum Aratum",
 "f31v":"Heracleum cervafolium",
 "f32r":"Mentastrum",
 "f32v":"Campanula, Rapunculus",
 "f33r":"",
 "f33v":"Scabiosa",
 "f34r":"[illeg.]",
 "f34v":"libanotis umbilifera",
 "f35r":"Leonuris? orchid root?",
 "f35v":"",
 "f36r":"",
 "f36v":"[illeg]",
 "f37r":"bladrian",
 "f37v":"",
 "f38r":"Aster luzei",
 "f38v":"",
 "f39r":"",
 "f39v":"[illeg.]",
 "f40r":"[illeg.]",
 "f40v":"Thistle, Jerusalem artichoke",
 "f41r":"Thistle",
 "f41v":"[illeg.], Fern, Maidenham fern???",
 "f42r":"Arum sagittarium",
 "f42v":"",
 "f43r":"Antemum Gnaphalium",
 "f43v":"polygonum?",
 "f44r":"veratrum",
 "f44v":"",
 "f45r":"",
 "f45v":"",
 "f46r":"asclepias roots",
 "f46v":"boragine",
 "f47r":"indian cucumber?",
 "f47v":"Doronicum, Pardalianchus",
 "f48r":"",
 "f48v":"",
 "f49r":"Tamus communis",
 "f49v":"lunaria",
 "f50r":"Artichoke, [illeg]",
 "f50v":"O'Neil: Umbellifera?",
 "f51r":"Mandrake",
 "f51v":"Cow's tongue, Licopsis, (Sedum majus, Hauswurz)?<br>",
 "f52r":"[illeg]",
 "f52v":"",
 "f53r":"Elecampane",
 "f53v":"hieracium",
 "f54r":"thistle",
 "f54v":"",
 "f55r":"",
 "f55v":"Elephants ear?",
 "f56r":"Boragine, echium",
 "f56v":"",
 "f57r":"",
 "f65r":"Rue, dropwort",
 "f65v":"Chamomile. St.Jacobskraut",
 "f66v":"primula?",
 "f87r":"",
 "f87v":"",
 "f90r1":"Holm",
 "f90r2":"[illeg] [illeg] Wermuth, Absinthium",
 "f90v2":"Xeranthium? Leaves of Osmu[n]da regalis",
 "f90v1":"not Löwenklau? Sp[h]ondylium ?",
 "f93r":"O'Neill Sunflower",
 "f93v":"",
 "f94r":"Botriculum",
 "f94v":"",
 "f95r1":"[illeg]",
 "f95r2":"",
 "f95v2":"Ban[e]berry? Actaea Waxberry",
 "f95v1":"Wermut, Artemisium",
 "f96r":"O'N",
 "f96v":"Smilax tracheia or Chenopodium",
 }